### ISSUE TITLE
handshake is never captured?

### ISSUE THREAD

**Issue by sersajar** [semeion/handshake-cracker#4]
In the window where ariodump-ng is running appears that the handshake is captured, I analyze file.cap in /tmp/handshake with pyrit and it seems ok. But the window with airodump-ng never stops or change... if I close it I return to handshake catcher window with its options, but the handshake is not shown in this window... what is suposed to do the program when captures the handshake??

Have a nice day.

**Comment by semeion** [comment]
pyrit use scapy 'analyze' function to check if the handshake was captured, and the latest version of scapy isn´t working very well in Arch linux and some distros. I don´t know the reason, so i switched from pyrit/scapy to wireshark-cli.

pyrit and scapy dependecies are removed and added wireshark-cli like a new dependency.

I hope it will work fine now. A feedback is welcome and sorry for the long time to fix it, i was waiting scapy get fixed but seems like it never will happens idk...

**Comment by semeion** [comment]
The script got updated and the wireshark, cowpatty, scapy and pyrit was removed like dependencies... The issues was fixed...
