### ISSUE TITLE
Actually cracking handshakes

### ISSUE THREAD

**Issue by bphd** [semeion/handshake-cracker#5]
Okay i got an handshake, i got dictionnaries, how to BEGIN the cracking process ???

**Comment by semeion** [comment]
Just select the handshake number and press [S]tart.

**Comment by semeion** [comment]
The format hccapx is crackeable using hashcat, the format cap is crackeable using aircrack-ng. You can convert between formats using the menus.

When ready, just select a entry by the number and press [S]tart session.
