### ISSUE TITLE
MDK4

### ISSUE THREAD

**Issue by areographe** [semeion/handshake-cracker#6]
Any chance of this tool being updated to support https://github.com/aircrack-ng/mdk4 ?

**Comment by semeion** [comment]
This script will not use any feature offered by MDK4, considering that MDK3 is only used to make the disconnection of the stations. But yes, in a future I will replace the MDK3 by MDK4, I just did not even because I'm out of time. Thanks for the interest.

**Comment by areographe** [comment]
Absolutely fair enough, I was just curious if there was a technical reason or if it was just a matter of not having time to make the changes. No rush and thanks for your prompt response
